# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-28 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websh', '0003_auto_20170928_1809'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserModel',
            new_name='User',
        ),
    ]
